version: 0.0
os: linux
files:
  - source: dist/myjavaapp
    destination: /var/www/myjavaapp
permissions:
  - object: /var/www/myjavaapp
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
  ApplicationStart:
    - location: deploy-scripts/Serverrestart.sh
      timeout: 300