version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11  # Using Amazon Corretto 11 as the Java runtime
    commands:
      - echo "Installing JDK 11"  # Replace with actual JDK installation commands if necessary
      - echo "Setting JDK 11 as default"
      - mvn package  # Command to build the Maven project and generate artifacts

artifacts:
  files:
    - '**/*'  # Include all JAR files produced by Maven as artifacts
  name: java-app-build  # Name for the build artifact
